Update login functionality, delete servlets, display servlet and file…
googleinterns/step2-2020 pull request #33
Opened 2020-07-13 18:35 UTC by Chronos34

… permission

2020-07-16 19:11 UTC, CharlesJ10 approved these changes

2020-07-16 22:01 UTC, HallM requested changes

2020-07-16 22:01 UTC, HallM commented on capstone/src/main/java/com/google/sps/servlets/APKUploadServlet.java
> +    if (!userService.isUserLoggedIn()) {return;}
You'll want to send a response back of sorts. This I believe would return an error that to the user would say something like request closed. Sending back a code 403 would be a better user experience to let the user know the issue is they are not logged in.

2020-07-16 22:01 UTC, HallM commented on capstone/src/main/java/com/google/sps/servlets/FileDeletionServlet.java
> +    if (!userService.isUserLoggedIn()) {return;}
Same 403 here.

2020-07-16 22:01 UTC, HallM commented on capstone/src/main/java/com/google/sps/servlets/FileDeletionServlet.java
> +    if (!deleteUnzippedApk(dataStore, fileName, currentUser.getUserId())) {return;}
Similar, but I would use a 404 here.

2020-07-16 22:01 UTC, HallM commented on capstone/src/main/java/com/google/sps/servlets/FileRetrievalServlet.java
> +    if (!userServices.isUserLoggedIn()) {return datastorage.prepare(new Query("Empty"));}
Another option could be to use Java's Optional class. The return could be an Optional<PreparedQuery>, then you'd return either
`Optional.empty()`
or
`Optional.of(datastorage.prepare(query));`
depending on if the user is logged in or not.

Then the use of this function above can skip trying to process entities.

2020-07-16 22:01 UTC, HallM commented on capstone/src/main/java/com/google/sps/servlets/SignInServlet.java
> +    if (userService.isUserLoggedIn()) {response.sendRedirect("/#/explore");}
Can use an else block or a similar style to the doPost where it does the condition and returns. The remainder of the function then can assume the logged in state.

2020-07-17 15:49 UTC, HallM approved these changes

2020-07-17 15:55 UTC, merged