Adebisi
googleinterns/step2-2020 pull request #34
Opened 2020-07-13 19:35 UTC by ziniblesssed

2020-07-13 20:59 UTC, Chronos34 approved these changes

2020-07-16 13:48 UTC, ananci approved these changes

2020-07-16 18:17 UTC, CharlesJ10 approved these changes

2020-07-16 18:32 UTC, HallM requested changes
LGTM, but sounds like we need #33 before this can be merged.

2020-07-17 15:57 UTC, HallM approved these changes

2020-07-17 15:57 UTC, HallM commented
#33 is merged now.

2020-07-17 16:19 UTC, merged