Test all functions in the parser library
googleinterns/step2-2020 pull request #55
Opened 2020-07-31 03:03 UTC by ziniblesssed

2020-07-31 15:19 UTC, Chronos34 approved these changes

2020-07-31 18:08 UTC, HallM requested changes

2020-07-31 18:08 UTC, HallM commented on capstone/src/main/java/com/google/sps/data/AndroidManifestParser.java
> +    return permissionsList;
For testability and readability, I would suggest created an ArrayList in this function, add all the permissions to it, then return that fresh ArrayList. The caller above would then use .addAll() to add everything to the other array list. Another option is to pass in an ArrayList to be modified by the function. It mostly helps with expectations of the user of the library who may call "getPermissions" with some random string not expecting the call to modify internal state of the parser.

2020-07-31 18:08 UTC, HallM commented on capstone/src/test/java/com/google/sps/AndroidManifestParserTest.java
> +        }
Much of this could be separated into a helper function that returns the populated byte[]. That would help reduce duplicated code in all the tests.

2020-08-03 17:21 UTC, CharlesJ10 approved these changes

2020-08-03 22:23 UTC, HallM approved these changes

2020-08-03 22:23 UTC, merged